version: 2.1
orbs:
  maven-build: circleci/maven@0.0.12
  heroku: circleci/heroku@0.0.10
workflows:
  version: 2.1
  # maven_test:
  #   jobs:
  #     - maven-build/test #  checkout, build, test, and upload test results
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git


