# version: 2.1
# orbs:
#   maven-build: circleci/maven@0.0.12
#   heroku: circleci/heroku@0.0.10
# workflows:
#   version: 2.1
#   maven_test:
#     jobs:
#       - maven-build/test #  checkout, build, test, and upload test results
#   heroku_deploy:
#     jobs:
#       - heroku/deploy-via-git


version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
jobs:
  mvn_build:
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
        auth:
          username: igorcooli
          password: Senhadodocker159
    steps:
      - checkout
      - run : mvn test
      - store_artifacts:
          path:  target
  heroku_deploy:
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
        auth:
          username: igorcooli
          password: Senhadodocker159
    steps:
      - heroku/deploy-via-git
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - mvn_build
      - heroku_deploy
        requires:
          - build