version: 2.1
orbs:
  maven-build: circleci/maven@0.0.12
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - maven-build/test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
