version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  mvn_test:
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
        auth:
          username: igorcooli
          password: Senhadodocker159
    steps:
      - checkout
      - run : mvn test
      - store_artifacts:
          path:  target
  sonar_analyze:
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
        auth:
          username: igorcooli
          password: Senhadodocker159
    steps:
      - checkout
      - run : 
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
      - store_artifacts:
          path:  target
workflows:
  version: 2
  build_and_analyze_and_deploy:
    jobs:
      - mvn_test
      - sonar_analyze:
          requires:
            - mvn_test
      - heroku/deploy-via-git:
          requires:
            - mvn_test