# version: 2.1
# orbs:
#   maven-build: circleci/maven@0.0.12
#   heroku: circleci/heroku@0.0.10
# workflows:
#   version: 2.1
#   maven_test:
#     jobs:
#       - maven-build/test #  checkout, build, test, and upload test results
#   heroku_deploy:
#     jobs:
#       - heroku/deploy-via-git


version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run : mvn test
      - store_artifacts:
          path:  target
      - heroku/deploy-via-git